version: "3.9"
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./src:/code
    environment:
      FLASK_ENV: development
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
  rediscommander:
    image: rediscommander/redis-commander
    ports:
      - 7080:80
    environment:
      - REDIS_HOST=redis
      - PORT=80
volumes:
  redis-data:
    driver: local
